### ISSUE TITLE
Allow pip version and export capability

### ISSUE THREAD

**Issue by Gijsreyn** [microsoft/winget-dsc#71]
### Description of the new feature / enhancement

The current `PythonPip3Dsc` module doesn't have the ability to specify a version when installing/uninstalling packages. It also doesn't support the export capability.

**Comment by Trenly** [comment]
[Policy] PythonPip3Dsc

**Comment by Gijsreyn** [comment]
@denelon Issue can be solved as per #72 :)

**Comment by Trenly** [comment]
Close with reason: Resolved;
